In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
import numpy as np

# Generate dummy sequential data
sequence = np.arange(0, 1000, 5)
time_steps = 10
X_train = []
y_train = []
for i in range(len(sequence) - time_steps):
    X_train.append(sequence[i:i + time_steps])
    y_train.append(sequence[i + time_steps])

# Reshape data for RNN input
# The original code had x_train instead of X_train, causing the issue.
# Keras expects X_train to have shape (num_samples, time_steps, num_features)
X_train = np.array(X_train).reshape(len(X_train), time_steps, 1)
y_train = np.array(y_train).reshape(len(y_train), 1)

# Create a simple RNN model
model = Sequential()
model.add(SimpleRNN(50, input_shape=(time_steps, 1), activation='relu'))
model.add(Dense(1))  # Output layer for regression

# Show model structure
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_7 (SimpleRNN)             │ (None, 50)                  │           2,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,651 (10.36 KB)

 Trainable params: 2,651 (10.36 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=250, batch_size=32)

Epoch 1/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1596.0533
Epoch 2/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 703.5886  
Epoch 3/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 296.8354 
Epoch 4/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 268.2516 
Epoch 5/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 149.0804 
Epoch 6/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 60.0862 
Epoch 7/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.3673
Epoch 8/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.2432
Epoch 9/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.2638 
Epoch 10/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1171 
Epoch 11/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.0719 
Epoch 12/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.2643 
Epoch 13/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.7641 
Epoch 14/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.0839 
Epoch 15/250
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.9739 
Epoch 1

In [ ]:
sequence[0:0+time_steps]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
sequence = np.arange(0,1000,5)
time_steps = 10
len(sequence)-time_steps
sequence


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515,
       520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580,
       585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645,
       650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710,
       715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775,
       780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840,
       845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 895, 90

In [ ]:
sequence[0+time_steps]

50

In [ ]:
x_train[0:2]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20],
        [25],
        [30],
        [35],
        [40],
        [45]],

       [[ 5],
        [10],
        [15],
        [20],
        [25],
        [30],
        [35],
        [40],
        [45],
        [50]]])

In [ ]:
y_train[0:2]

array([[50],
       [55]])